name: Test Rails Template

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_template:
    runs-on: ubuntu-latest
    env:
      CI: true  # Ensures Rails runs in CI mode (skips prompts, etc.)
      DB: sqlite3  # Use SQLite for simplicity in CI

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true  # Caches gems for faster runs

      - name: Install Rails and dependencies
        run: gem install rails -v 7.1.5.1 # <-- ADD -v 7.1.5.1 HERE

      - name: Generate app from template
        run: |
          rails new dummy_app \
            -m template.rb \
            -d sqlite3 \
            --skip-test \
            --force \
            --skip-binstubs
             --skip-kamal  # <-- ADD THIS LINE
          cat dummy_app/Gemfile.lock
          rails -v
          cd dummy_app
          bin/rails runner "puts '✅ Template applied successfully'"

      - name: Verify Turbo/Stimulus (if needed)
        if: false  # Disabled by default; enable if your template uses JS
        run: |
          cd dummy_app
          bin/rails turbo:install stimulus:install